security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

            logout:
                target: /showAllPosts
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/showPost, role: ROLE_USER }
        - { path: ^/addPost, role: ROLE_USER }
        - { path: ^/addCategory, role: ROLE_ADMIN }
        - { path: ^/showAllCategories, role: ROLE_ADMIN }
        - { path: "^/profile/view/{id}", role: ROLE_USER }
        - { path: "^/addCommentToPostWithId/{id}", role: ROLE_USER }
        - { path: "^/showAllCommentsToPostWithId/{id}", role: ROLE_USER }
        - { path: "^/showPost/{id}", role: ROLE_USER }
        - { path: ^/profile/, role: ROLE_USER }
        - { path: ^/profile/edit, role: ROLE_USER }
        - { path: ^/profile/change-password, role: ROLE_USER }